-- WordUp Supabase database
-- Run this whole file in Supabase SQL Editor.

create table if not exists public.user_words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  meaning text not null,
  pron text,
  example text,
  level text not null default 'B1' check (level in ('B1','B2','C1')),
  created_at timestamptz not null default now()
);

create table if not exists public.learned_words (
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, word)
);

alter table public.user_words enable row level security;
alter table public.learned_words enable row level security;

drop policy if exists "Users can read own words" on public.user_words;
create policy "Users can read own words"
on public.user_words for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own words" on public.user_words;
create policy "Users can insert own words"
on public.user_words for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own words" on public.user_words;
create policy "Users can delete own words"
on public.user_words for delete to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own learned" on public.learned_words;
create policy "Users can read own learned"
on public.learned_words for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own learned" on public.learned_words;
create policy "Users can insert own learned"
on public.learned_words for insert to authenticated
with check (auth.uid() = user_id);

-- Users can never read or modify another user's rows because of the RLS policies above.
